### ISSUE TITLE
Why deleting???

### ISSUE THREAD

**Issue by Exeedy** [Keeperdy/PS4-Host-ESP8266-Firmware-for-5.05#2]

**Comment by Keeperdy** [comment]
Deleting what? Your statement about the code? It was just removed to closed question after c0d3m4st4's comment, you can see it here https://github.com/Keeperdy/PS4-Host-ESP8266-Firmware-for-5.05/issues/1

**Comment by Keeperdy** [comment]
Are you satisfied with my answers? Can I close this issue or you will start again another thread accusing me in stealing the code? If you were wrong (everybody sometimes is), have an honour to admit your mistake and at least make a reply to the thread you created!!!
